environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\.ci\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

cache:
  - "C:\\wheels"
  - "node_modules"
  - "C:\\Users\\appveyor\\AppData\\Local\\coala-bears\\coala-bears"
  - "C:\\Users\\appveyor\\AppData\\Roaming\\nltk_data"

branches:  # Only build official branches, PRs are built anyway.
  only:
    - master
    - /release.*/

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PATH=C:\\Program\ Files\\Java\\jdk1.7.0\\bin;%PATH%"

  # language-tool needs the registry tweaked here since it determines the java
  # version wrong (since appveyor has both, 1.7 and 1.8 in x86 and x64).
  - "SET KEY_NAME=HKLM\\Software\\JavaSoft\\Java Runtime Environment"
  - "REG add \"%KEY_NAME%\" /v CurrentVersion /t REG_SZ /d 1.7 /f"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - "%CMD_IN_ENV% pip install wheel"
  # Create c:/wheels if it does not exist.
  - ps: If ( -not (Test-Path C:\\wheels) )  { mkdir C:\\wheels }
  - ECHO "Cached wheels:"
  - ps: "ls \"C:\\wheels\""
  - "%CMD_IN_ENV% pip wheel --use-wheel --wheel-dir C:\\wheels --find-links C:\\wheels -r test-requirements.txt"
  - "%CMD_IN_ENV% pip wheel --use-wheel --wheel-dir C:\\wheels --find-links C:\\wheels -r requirements.txt"
  - "%CMD_IN_ENV% pip install --find-links=C:\\wheels -r test-requirements.txt"
  - "%CMD_IN_ENV% pip install --find-links=C:\\wheels -r requirements.txt"
  - "CALL .ci/deps.nltk.cmd"

  - ps: "Install-Product node ''"  # Use latest node v5.x.x
  - "npm config set loglevel warn"
  - "npm install"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Clang DLLs x64 were nowadays installed, but the x64 version hangs, so we
  # exclude according tests. See https://github.com/appveyor/ci/issues/495 and
  # https://github.com/appveyor/ci/issues/688
  - "%CMD_IN_ENV% python -m pytest --cov -k \"not ClangASTPrintBear and not ClangCloneDetectionBear and not ClangComplexityBear and not ClangCountVectorCreator and not ClangCountingConditions\""
  - "%CMD_IN_ENV% python setup.py install"
